package com.likeminds.chatmm.buysellwidget.domain.model

import com.google.gson.annotations.SerializedName

data class Response(
//    var EqORFO: Int? = 0,
//    var ExchangeSegment: String? = "",
//    var Expiry: Int? = 0,
//    var InstrumentName: String? = "",
//    var IsFnOAvailable: Boolean? = false,
//    var IsIndex: Int? = 0,
//    var MWTag: String? = "",
//    var MarketLot: Int? = 0,
//    var Multiplier: Double? = 0.0,
//    var OptionType: String? = "",
//    var PriceDivisor: Int? = 0,
//    var PriceTick: Double? = 0.0,
//    var SecDesc: String? = "",
//    var SecName: String? = "",
//    var SecNameNew: String? = "",
//    var SegmentId: Int? = 0,
//    var Series: String? = "",
//    var StrikePrice: Double? = 0.0,
//    var Symbol: String? = "",
//    var Token: Int? = 0,
//    var sExpiry: String? = ""

    @SerializedName("EqORFO") var eqORFO: Int? = null,
    @SerializedName("ExchangeSegment") var exchangeSegment: String? = null,
    @SerializedName("Expiry") var expiry: Int? = null,
    @SerializedName("InstrumentName") var instrumentName: String? = null,
    @SerializedName("IsIndex") var isIndex: Int? = null,
    @SerializedName("MarketLot") var marketLot: Int? = null,
    @SerializedName("OptionType") var optionType: String? = null,
    @SerializedName("PriceDivisor") var priceDivisor: Int? = null,
    @SerializedName("PriceTick") var priceTick: Int? = null,
    @SerializedName("sExpiry") var sExpiry: String? = null,
    @SerializedName("SecDesc") var secDesc: String? = null,
    @SerializedName("SecName") var secName: String? = null,
    @SerializedName("SegmentId") var segmentId: Int? = null,
    @SerializedName("Series") var series: String? = null,
    @SerializedName("StrikePrice") var strikePrice: Float? = null,
    @SerializedName("Symbol") var symbol: String? = null,
    @SerializedName("Token") var token: Int? = null,
    @SerializedName("MWTag") var mwTag: String? = "",
    @SerializedName("isAdded") var isAdded: Boolean = false,
)